import Foundation

enum HangoutsMockData {
    static func sample(now: Date = Date()) -> [HangoutItem] {
        [
            HangoutItem(
                id: 101,
                sourceType: .hangout,
                title: "Coffee and Co-Work Sprint",
                description: "Bring your laptop. Focus block, then quick social break.",
                vibe: .chill,
                cityName: "Berlin",
                locationName: "Mitte Bean Lab",
                hostName: "nina",
                startAt: now.addingTimeInterval(60 * 35),
                endAt: now.addingTimeInterval(60 * 135),
                capacity: 8,
                approvedCount: 5,
                isLive: false,
                isMicro: true,
                isJoined: true,
                participantNames: ["Luca", "Maya", "Sam", "Alex", "Nora"],
                coverImageData: nil,
                coverSeed: 1,
                distanceKm: 1.1,
                priceTier: .free
            ),
            HangoutItem(
                id: 110,
                sourceType: .hangout,
                title: "Host Mode Demo · Sunset Social Lab",
                description: "You are hosting this one. Open it to review incoming join requests and manage attendees.",
                vibe: .chill,
                cityName: "Berlin",
                locationName: "Canal House Terrace",
                hostName: "you",
                startAt: now.addingTimeInterval(60 * 48),
                endAt: now.addingTimeInterval(60 * 168),
                capacity: 8,
                approvedCount: 3,
                isLive: false,
                isMicro: false,
                isJoined: true,
                participantNames: ["You", "Nora", "Milo"],
                coverImageData: nil,
                coverSeed: 10,
                distanceKm: 1.6,
                priceTier: .free
            ),
            HangoutItem(
                id: 102,
                sourceType: .offer,
                title: "Sunset Rooftop Drinks",
                description: "Golden hour, easy music, and no pressure networking.",
                vibe: .drinks,
                cityName: "Berlin",
                locationName: "Skyline Terrace",
                hostName: "kai",
                startAt: now.addingTimeInterval(60 * 95),
                endAt: now.addingTimeInterval(60 * 245),
                capacity: 12,
                approvedCount: 10,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Jo", "Elena", "Max", "Iris", "Tom", "Lena"],
                coverImageData: nil,
                coverSeed: 2,
                distanceKm: 3.8,
                priceTier: .budget
            ),
            HangoutItem(
                id: 103,
                sourceType: .event,
                title: "Creative Deep Talk Circle",
                description: "Small group conversation around goals, blocks, and ideas.",
                vibe: .deepTalk,
                cityName: "Berlin",
                locationName: "Studio Hall 4",
                hostName: "ruben",
                startAt: now.addingTimeInterval(-60 * 20),
                endAt: now.addingTimeInterval(60 * 90),
                capacity: 6,
                approvedCount: 4,
                isLive: true,
                isMicro: true,
                isJoined: true,
                participantNames: ["Lia", "Noah", "Omar", "Sia"],
                coverImageData: nil,
                coverSeed: 3,
                distanceKm: 2.4,
                priceTier: .free
            ),
            HangoutItem(
                id: 108,
                sourceType: .event,
                title: "Afterparty Circle · Neo-Soul Jam",
                description: "Small post-event meetup to keep the vibe going after the concert.",
                vibe: .drinks,
                cityName: "Berlin",
                locationName: nil,
                hostName: "event host",
                startAt: now.addingTimeInterval(60 * 70),
                endAt: now.addingTimeInterval(60 * 180),
                capacity: 10,
                approvedCount: 6,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Luca", "Iris", "Milo", "Elena", "Kai", "Nora"],
                coverImageData: nil,
                coverSeed: 8,
                distanceKm: 2.9,
                priceTier: .budget
            ),
            HangoutItem(
                id: 109,
                sourceType: .offer,
                title: "Community Table · Rooftop Voucher Night",
                description: "People redeeming the venue voucher can join this social table together.",
                vibe: .chill,
                cityName: "Berlin",
                locationName: nil,
                hostName: "venue team",
                startAt: now.addingTimeInterval(60 * 130),
                endAt: now.addingTimeInterval(60 * 240),
                capacity: 12,
                approvedCount: 7,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Tom", "Maya", "Alex", "Rina", "Jo", "Sara", "Ben"],
                coverImageData: nil,
                coverSeed: 9,
                distanceKm: 3.1,
                priceTier: .free
            ),
            HangoutItem(
                id: 104,
                sourceType: .hangout,
                title: "Street Photo Walk",
                description: "Urban walk with simple prompts. Any phone camera works.",
                vibe: .activity,
                cityName: "Berlin",
                locationName: "Hackescher Markt",
                hostName: "tina",
                startAt: now.addingTimeInterval(60 * 220),
                endAt: now.addingTimeInterval(60 * 340),
                capacity: 10,
                approvedCount: 6,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Ben", "Rina", "Faye", "Pablo", "Milo", "Sara"],
                coverImageData: nil,
                coverSeed: 4,
                distanceKm: 4.9,
                priceTier: .free
            ),
            HangoutItem(
                id: 105,
                sourceType: .offer,
                title: "Late Night Ramen Run",
                description: "Post-work ramen and spontaneous city stories.",
                vibe: .foodie,
                cityName: "Berlin",
                locationName: "Ramen Shiro",
                hostName: "jana",
                startAt: now.addingTimeInterval(60 * 310),
                endAt: now.addingTimeInterval(60 * 420),
                capacity: 7,
                approvedCount: 7,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Yuki", "Ali", "Cleo", "Nico", "Rory", "Zoe", "Ian"],
                coverImageData: nil,
                coverSeed: 5,
                distanceKm: 5.2,
                priceTier: .premium
            ),
            HangoutItem(
                id: 106,
                sourceType: .event,
                title: "Morning Run + Matcha",
                description: "Easy pace group run, then cool-down at a nearby cafe.",
                vibe: .sporty,
                cityName: "Berlin",
                locationName: "Tiergarten East Gate",
                hostName: "leo",
                startAt: now.addingTimeInterval(60 * 60 * 14),
                endAt: now.addingTimeInterval(60 * 60 * 16),
                capacity: 14,
                approvedCount: 8,
                isLive: false,
                isMicro: false,
                isJoined: true,
                participantNames: ["Emi", "Gio", "Hana", "Ari", "Pia", "Oli", "Mina", "Vik"],
                coverImageData: nil,
                coverSeed: 6,
                distanceKm: 7.0,
                priceTier: .budget
            ),
            HangoutItem(
                id: 107,
                sourceType: .hangout,
                title: "Board Games and Burgers",
                description: "Two tables, quick rounds, and good food in between.",
                vibe: .chill,
                cityName: "Berlin",
                locationName: "Kreuzberg Social Club",
                hostName: "sven",
                startAt: now.addingTimeInterval(60 * 60 * 26),
                endAt: now.addingTimeInterval(60 * 60 * 29),
                capacity: 9,
                approvedCount: 3,
                isLive: false,
                isMicro: false,
                isJoined: false,
                participantNames: ["Ivy", "Dan", "Mo"],
                coverImageData: nil,
                coverSeed: 7,
                distanceKm: 8.7,
                priceTier: .budget
            )
        ]
    }
}
